In [1]:
#Import Standard Libraries
import pandas as pd
import matplotlib.pyplot as plt

import numpy as np
%matplotlib inline

# Custom Function and Transformers

In [2]:
#Function to Import Data

def import_data(path, sep,dropna=True, drop_duplicates=True):
    data = pd.read_csv(path, sep)
    print("Banyaknya baris dan kolom", data.shape)
    print("Banyaknya data duplicate", data.duplicated().sum())
    data = data.drop_duplicates() if drop_duplicates else data
    data = data.dropna() if dropna else data
    #print(data.head())
    return data

In [3]:
#Function to Extract Input and Output

def extract_input_output(data, output):
    y = data[output]
    x = data.drop(output, axis=1)
    #print(x.columns) #optional
    #print(y.head()) #optional
    return x,y

In [4]:
#function to split train test data (default test_size = 0.4)
from sklearn.model_selection import train_test_split

def train_test_data(x,y, _test_size = 0.4): 
    x_train, x_test, y_train, y_test = train_test_split(x,y, test_size =_test_size,
                                                        random_state =100)
   # print(x_train.head(), y_train.head()) #
    #print(x_test.head(), y_test.head()) #
    return x_train, x_test, y_train, y_test

In [5]:
#Function to evaluate score
from sklearn.metrics import accuracy_score

def scoring(model) :
    y_predict = model.predict(x_train)
    print("Model Score based on training data")
    print(accuracy_score(y_train, y_predict))
    y_predict = model.predict(x_test)
    print("Model Score based on test data")
    print(accuracy_score(y_test, y_predict))


In [6]:
from sklearn.base import TransformerMixin #gives fit_transform method for free
class MyLabelBinarizer(TransformerMixin):
    def __init__(self, *args, **kwargs):
        self.encoder = LabelBinarizer(*args, **kwargs)
    def fit(self, x, y=0):
        self.encoder.fit(x)
        return self
    def transform(self, x, y=0):
        return self.encoder.transform(x)

In [7]:
from sklearn.base import BaseEstimator, TransformerMixin
class DataFrameSelector(BaseEstimator, TransformerMixin):
  def __init__(self, attribute_names):
    self.attribute_names = attribute_names
  def fit(self, X, y=None):
    return self
  def transform(self, X):
    return X[self.attribute_names].values

# Pre Processing Pipeline

In [8]:
df = import_data('../Bagian C/datasets/iris.csv',',')

Banyaknya baris dan kolom (150, 5)
Banyaknya data duplicate 3


In [9]:
df.head()

sepal_length   sepal_width   petal_length   petal_width  species
0           5.1           3.5            1.4           0.2   setosa
1           4.9           3.0            1.4           0.2   setosa
2           4.7           3.2            1.3           0.2   setosa
3           4.6           3.1            1.5           0.2   setosa
4           5.0           3.6            1.4           0.2   setosa

In [10]:
x, y = extract_input_output(df, ' species')

In [11]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import FeatureUnion

num_attribs = list(x)


preprocessor = Pipeline([
#     ('selector', DataFrameSelector(num_attribs)),
    ('imputer', SimpleImputer(strategy="median")),
    #('attribs_adder', CombinedAttributesAdder()),
    ('std_scaler', StandardScaler()),
  ])

# cat_pipeline = Pipeline([
#     ('selector', DataFrameSelector(cat_attribs)),
#     ('label_binarizer', MyLabelBinarizer()),
#   ])

# preprocessor = FeatureUnion(transformer_list=[
#     ("num_pipeline", num_pipeline),
#     ("cat_pipeline", cat_pipeline),
#   ])

# Machine Learning Pipeline

In [12]:
from clf.mlp import MyMlp
from clf.utils import read_csv, scale_data

In [13]:
input_layer = len(list(x))
print(input_layer)
output_layer = len(set(y))
print(output_layer)
hidden_layer = [4, 3]
print(hidden_layer)

4
3
[4, 3]


In [16]:
myclf = MyMlp(input_layer, hidden_layer, output_layer, epochs=2500)

In [ ]:
from sklearn.linear_model import LogisticRegression
pipeline = Pipeline([
    ('processor', preprocessor), #Step1 - preprocess data
    ('clf', LogisticRegression()) #step2 - classifier (default : LogisticRegression )
])

from sklearn.model_selection import cross_validate
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

clfs = []
clfs.append(myclf)
# clfs.append(SVC())
# clfs.append(KNeighborsClassifier(n_neighbors=3))
# clfs.append(DecisionTreeClassifier())
# clfs.append(RandomForestClassifier())
# clfs.append(GradientBoostingClassifier())

for classifier in clfs:
    pipeline.set_params(clf = classifier)
    scores = cross_validate(pipeline, x.values, y.values, cv=5)
    print('---------------------------------')
    print(str(classifier))
    print('-----------------------------------')
    for key, values in scores.items():
            print(key,' mean ', values.mean())
            print(key,' std ', values.std())
    print(scores)

[0.48439518 0.4137771  0.2409445 ]
[0.48439518 0.4137771  0.2409445 ]
[0.48439517 0.41377711 0.24094452]
[0.11237044 0.27862029 0.68128179]
[0.11237044 0.27862029 0.68128179]
[0.11237044 0.27862029 0.68128179]
[0.73579005 0.25780242 0.05802729]
[0.73606992 0.25792291 0.05792918]
[0.70552954 0.24660897 0.06955473]
